---
# tasks file for configure_collectd

- include: centos.yml
  when: ansible_distribution == 'CentOS'

#- include: amazon.yml
#  when: ansible_distribution == 'Amazon'

- name: Push collectd.conf template
  template:
    src: collectd.conf
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: 0755

  notify: Restart collectd 

- name: Flush restart collectd handler
  meta: flush_handlers  
