---
# tasks file for install_jenkins

- name: Install jenkins repo
  yum_repository:
    name: "{{ jenkins_repo_name }}"
    description: Jenkins repo
    baseurl: "{{ jenkins_repo }}"

- name: Get rpm key
  rpm_key:
    state: present
    key: "{{ jenkins_key }}"

- name: Upgrade yum packages
  yum: 
    name: '*'
    state: latest

- name: Install jenkins
  yum: 
    name: 
      - jenkins
      - java-1.8.0-openjdk-devel

- name: Start jenkins
  systemd:
    name: jenkins
    state: started

- name: Open port 8080
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: Restart firewalld
  systemd:
    name: firewalld
    state: restarted
