---
# tasks file for install_terraform

- name: "Get terraform version {{ terraform_version }} package from terraform repo {{ terraform_install_package_home }}"
  get_url:
    url: "{{ terraform_install_package_home }}/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /tmp
    mode: '0775'

- name: Ensure terraform install dir exists
  file:
    path: "{{ terraform_install_dir }}"
    state: directory
    mode: '0775'

- name: Unzip terraform package
  unarchive: 
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ terraform_install_dir }}"
    remote_src: yes

- name: Set perms on terraform binary
  file:
    path: "{{ terraform_install_dir }}/terraform"
    owner: root
    group: root
    mode: '0775' 

- name: Test terraform runs OK
  command: "{{ terraform_install_dir }}/terraform -help"
  register: cmd_output

- debug: msg="{{cmd_output.stdout}}"
    
