---
# tasks file for install_collectd
- include: amazon.yml
  when: ansible_distribution == 'Amazon'

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Install collectd
  yum:
    name: collectd
    state: present

